import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://eweb-1383.staging.zweb.com.br/#/sign-in');
    await page.getByRole('textbox', { name: 'E-mail' }).click();
    await page.getByRole('textbox', { name: 'E-mail' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'E-mail' }).fill('T');
    await page.getByRole('textbox', { name: 'E-mail' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'E-mail' }).fill('Testes');
    await page.getByRole('textbox', { name: 'E-mail' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'E-mail' }).fill('TestesQ');
    await page.getByRole('textbox', { name: 'E-mail' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'E-mail' }).fill('TestesQa@gmail.com');
    await page.locator('input[type="password"]').click();
    await page.locator('input[type="password"]').press('CapsLock');
    await page.locator('input[type="password"]').fill('S');
    await page.locator('input[type="password"]').press('CapsLock');
    await page.locator('input[type="password"]').fill('Sarco2020!');
    await page.getByRole('button', { name: 'Entrar' }).click();
    await page.getByRole('link', { name: 'Produtos' }).click();
    await page.getByRole('link', { name: 'Cadastrar produto' }).first().click();
    await page.getByRole('textbox', { name: 'Descrição*' }).click();
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('T');
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('Teste ');
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('Teste P');
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('Teste Produto ');
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('Teste Produto CO');
    await page.getByRole('textbox', { name: 'Descrição*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Descrição*' }).fill('Teste Produto Com grade');
    await page.locator('[id="product.hasVariations"]').check();
    await page.getByRole('button', { name: 'Dados fiscais' }).click();
    await page.getByRole('button', { name: 'Selecione a origem' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).click();
    await page.getByRole('textbox', { name: 'fiscal.produto.origem-' }).fill('0');
    await page.getByRole('textbox', { name: 'fiscal.produto.origem-' }).press('Enter');
    await page.getByRole('button', { name: 'Selecione a origem' }).click();
    await page.getByRole('button').filter({ hasText: '0 - Nacional, exceto as' }).dblclick();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
    await page.getByRole('button').filter({ hasText: '00 - Tributada' }).first().click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('button', { name: '0 - Nacional, exceto as' }).click();
    await page.getByRole('textbox', { name: 'fiscal.produto.origem-' }).fill('0');
    await page.getByRole('textbox', { name: 'fiscal.produto.origem-' }).press('Enter');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByRole('textbox', { name: 'fiscal.produto.CSTNaoContribuinte-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CSTNaoContribuinte-searchbox' }).press('Enter');
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').press('Enter');
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').fill('5102');
    await page.getByRole('button', { name: '5102' }).click();
    await page.getByRole('button', { name: '5102' }).dblclick();
    await page.getByRole('button', { name: 'Selecione um NCM' }).click();
    await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
    await page.getByRole('button').filter({ hasText: '5000 - Saídas ou prestações' }).nth(1).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').fill('5102');
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').press('Tab');
    await page.getByText('Selecione um CFOP5000 - Saí').click();
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').fill('5102');
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').press('Enter');
    await page.getByText('Selecione um CFOP5000 - Saí').click();
    await page.getByRole('button').filter({ hasText: '5000 - Saídas ou prestações' }).nth(1).click();
    await page.getByRole('button').filter({ hasText: '5000 - Saídas ou prestações' }).nth(1).dblclick();
    await page.getByRole('button', { name: '5102 - Venda de mercadoria' }).click();
    await page.getByRole('button', { name: '5102 - Venda de mercadoria' }).click();
    await page.getByRole('button', { name: '5102 - Venda de mercadoria' }).getByPlaceholder('Selecione um CFOP').fill('5102');
    await page.getByRole('button', { name: '5102 5102 - Venda de' }).click();
    await page.getByRole('button', { name: '5102 5102 - Venda de' }).dblclick();
    await page.getByRole('button', { name: '5102 5102 - Venda de' }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('Enter');
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('Tab');
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).dblclick();
    await page.getByRole('button', { name: 'Selecione um NCM' }).click();
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).dblclick();
    await page.getByRole('button', { name: '5102', exact: true }).dblclick();
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).dblclick();
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('Tab');
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: 'Selecione um NCM' }).click();
    await page.getByRole('textbox', { name: 'fiscal.produto.NCM-searchbox' }).fill('000000');
    await page.getByRole('button', { name: '000000' }).click();
    await page.locator('#fiscalData > .accordion-header').click();
    await page.getByRole('button', { name: 'Selecione um NCM' }).click();
    await page.getByRole('textbox', { name: 'fiscal.produto.NCM-searchbox' }).fill('0000000');
    await page.getByRole('button', { name: '0000000' }).click();
    await page.getByRole('button', { name: '0000000' }).click();
    await page.getByRole('button', { name: 'Selecione um CFOP' }).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFE"]').fill('5102');
    await page.getByRole('button', { name: '5102', exact: true }).click();
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('ArrowDown');
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('ArrowDown');
    await page.getByRole('button', { name: '5102', exact: true }).getByPlaceholder('Selecione um CFOP').press('Enter');
    await page.getByRole('button', { name: '5102 - Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5501, 5502, 5504 e 5505', exact: true }).getByPlaceholder('Selecione um CFOP').press('Enter');
    await page.getByRole('button', { name: '5102 - Venda de mercadoria' }).nth(1).click();
    await page.locator('[id="product.fiscal.produto.CFOPNFCE"]').press('Enter');
    await page.getByRole('textbox', { name: 'fiscal.produto.NCM-searchbox' }).fill('000000');
    await page.getByRole('textbox', { name: 'fiscal.produto.NCM-searchbox' }).press('Enter');
    await page.getByRole('button', { name: 'Selecione um CST' }).first().click();
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByText('Selecione um CST00 -').click();
    await page.getByRole('button').filter({ hasText: '00 - Tributada' }).first().click();
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByText('Selecione um CST00 -').click();
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByText('Selecione um CST00 -').click();
    await page.getByRole('button').filter({ hasText: '00 - Tributada' }).first().dblclick();
    await page.getByRole('button').filter({ hasText: '00 - Tributada' }).first().click();
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByRole('textbox', { name: 'fiscal.produto.CSTNaoContribuinte-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CSTNaoContribuinte-searchbox' }).press('ArrowDown');
    await page.getByRole('textbox', { name: 'fiscal.produto.CSTNaoContribuinte-searchbox' }).press('Enter');
    await page.getByText('Selecione um CST00 -').click();
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).fill('00');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('ArrowDown');
    await page.getByRole('textbox', { name: 'fiscal.produto.CST-searchbox' }).press('Enter');
    await page.getByRole('button', { name: 'Reforma tributária' }).click();
    await page.getByRole('button').nth(3).click();
    await page.locator('#classTribIBSCBS').press('ArrowDown');
    await page.locator('#classTribIBSCBS').press('Enter');
    await page.getByRole('button', { name: 'Grade' }).click();
    await page.getByRole('button').filter({ hasText: 'VerdePretoAZUL-CLAROAzul' }).click();
    await page.locator('[id="variation.color"]').press('Enter');
    await page.locator('[id="variation.size"]').press('ArrowUp');
    await page.locator('[id="variation.size"]').press('Enter');
    await page.getByRole('button').filter({ hasText: 'VerdePretoAZUL-CLAROAzul' }).click();
    await page.locator('[id="variation.color"]').press('ArrowUp');
    await page.locator('[id="variation.color"]').press('Enter');
    await page.locator('[id="variation.size"]').press('Enter');
    await page.locator('#z_app_content_container').getByRole('button', { name: 'Salvar' }).click();
    await page.locator('#z_app_header_wrapper').getByText('Fiscal', { exact: true }).click();
    await page.getByRole('link', { name: 'NF-e' }).click();
    await page.getByRole('link', { name: 'Cadastrar NF-e' }).first().click();
    await page.getByRole('button').filter({ hasText: 'Venda de mercadoriaVenda de' }).click();
    await page.locator('#z-select-42083').press('ArrowDown');
    await page.locator('#z-select-42083').press('Enter');
    await page.getByRole('button', { name: 'Normal' }).getByLabel('-searchbox').press('Enter');
    await page.getByRole('button', { name: 'TestesQa@gmail.com' }).getByLabel('-searchbox').press('Enter');
    await page.getByRole('button', { name: 'Destinatário' }).click();
    await page.getByRole('button').filter({ hasText: /^Nenhuma opção encontradaNenhuma opção encontrada$/ }).click();
    await page.getByLabel('Destinatário').getByRole('textbox', { name: '-searchbox' }).press('Enter');
    await page.getByRole('button', { name: 'Itens R$' }).click();
    await page.getByRole('button').filter({ hasText: 'Digite descrição, código, có' }).click();
    await page.getByLabel('Itens R$').getByRole('textbox', { name: '-searchbox' }).fill('teste');
    await page.getByLabel('Itens R$').getByRole('textbox', { name: '-searchbox' }).press('Enter');
    await page.getByRole('textbox', { name: 'Quantidade' }).press('Enter');
    await page.getByRole('textbox', { name: 'Valor unitário R$' }).fill('5,000');
    await page.getByRole('textbox', { name: 'Valor unitário R$' }).press('Enter');
    await page.getByRole('textbox', { name: 'Desconto' }).press('Enter');
    await page.locator('div').filter({ hasText: /^Produto para consumidor final$/ }).nth(2).click();
    await page.getByRole('button', { name: 'Transmitir' }).click();
    await page.locator('#modal-wrapper').getByRole('button', { name: 'Transmitir' }).click();
    await page.getByText('- Venda de mercadoria').first().click({
        button: 'right'
    });
    const page1Promise = page.waitForEvent('popup');
    await page.locator('#menuId a').filter({ hasText: 'Visualizar DANFE' }).click();
    const page1 = await page1Promise;
    await page.getByText('- Venda de mercadoria').first().click({
        button: 'right'
    });
    const page2Promise = page.waitForEvent('popup');
    await page.locator('#menuId a').filter({ hasText: 'Gerar XML' }).click();
    const page2 = await page2Promise;
});
